version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    env_file:
      - .env
      - .env.local
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  worker:
    build: .
    environment:
      NODE_ENV: production
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-4}
      QUEUE_NAME: ${QUEUE_NAME}
      DATABASE_URL: ${DATABASE_URL}
    env_file: .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
